services:
  users-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - MONGO_URI=mongodb://host.docker.internal:27017/customer-master
      - REDIS_URL=redis://redis-server:6379
      - RABBITMQ_URL=amqp://rabbitmq-server:5672
    depends_on:
      - redis-server
      - mongo-db
      - rabbitmq-server

  redis-server:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq-server:
    image: rabbitmq:4-management
    ports:
      - "15672:15672" 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  rabbitmq-data:
